services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    container_name: billing-engine-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      CONFIG_PATH: "/app/files/config/app/config.yaml"
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: toor
      DB_NAME: billing
    volumes:
      - ./files/config:/app/files/config

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    container_name: billing-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: billing
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d billing"]
      interval: 2s
      timeout: 3s
      retries: 15
      start_period: 5s
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
