// Code generated by MockGen. DO NOT EDIT.
// Source: ./loanoutstanding.go

// Package mockservice is a generated GoMock package.
package mockservice

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	loanoutstanding "github.com/michaeltansy/billing-engine/internal/loanoutstanding"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetOutstanding mocks base method.
func (m *MockService) GetOutstanding(ctx context.Context, r loanoutstanding.Request) (loanoutstanding.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOutstanding", ctx, r)
	ret0, _ := ret[0].(loanoutstanding.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOutstanding indicates an expected call of GetOutstanding.
func (mr *MockServiceMockRecorder) GetOutstanding(ctx, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOutstanding", reflect.TypeOf((*MockService)(nil).GetOutstanding), ctx, r)
}
