// Code generated by MockGen. DO NOT EDIT.
// Source: ./service.go

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	loan "github.com/michaeltansy/billing-engine/internal/loan"
	payment "github.com/michaeltansy/billing-engine/internal/payment"
)

// MockDBStore is a mock of DBStore interface.
type MockDBStore struct {
	ctrl     *gomock.Controller
	recorder *MockDBStoreMockRecorder
}

// MockDBStoreMockRecorder is the mock recorder for MockDBStore.
type MockDBStoreMockRecorder struct {
	mock *MockDBStore
}

// NewMockDBStore creates a new mock instance.
func NewMockDBStore(ctrl *gomock.Controller) *MockDBStore {
	mock := &MockDBStore{ctrl: ctrl}
	mock.recorder = &MockDBStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBStore) EXPECT() *MockDBStoreMockRecorder {
	return m.recorder
}

// BeginTx mocks base method.
func (m *MockDBStore) BeginTx(ctx context.Context) (Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx)
	ret0, _ := ret[0].(Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockDBStoreMockRecorder) BeginTx(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockDBStore)(nil).BeginTx), ctx)
}

// FindPaymentByKey mocks base method.
func (m *MockDBStore) FindPaymentByKey(ctx context.Context, loanID int64, key string) (*payment.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPaymentByKey", ctx, loanID, key)
	ret0, _ := ret[0].(*payment.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPaymentByKey indicates an expected call of FindPaymentByKey.
func (mr *MockDBStoreMockRecorder) FindPaymentByKey(ctx, loanID, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPaymentByKey", reflect.TypeOf((*MockDBStore)(nil).FindPaymentByKey), ctx, loanID, key)
}

// ReplayState mocks base method.
func (m *MockDBStore) ReplayState(ctx context.Context, loanID, paymentID int64) (ReplayState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplayState", ctx, loanID, paymentID)
	ret0, _ := ret[0].(ReplayState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplayState indicates an expected call of ReplayState.
func (mr *MockDBStoreMockRecorder) ReplayState(ctx, loanID, paymentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplayState", reflect.TypeOf((*MockDBStore)(nil).ReplayState), ctx, loanID, paymentID)
}

// MockTx is a mock of Tx interface.
type MockTx struct {
	ctrl     *gomock.Controller
	recorder *MockTxMockRecorder
}

// MockTxMockRecorder is the mock recorder for MockTx.
type MockTxMockRecorder struct {
	mock *MockTx
}

// NewMockTx creates a new mock instance.
func NewMockTx(ctrl *gomock.Controller) *MockTx {
	mock := &MockTx{ctrl: ctrl}
	mock.recorder = &MockTxMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTx) EXPECT() *MockTxMockRecorder {
	return m.recorder
}

// Commit mocks base method.
func (m *MockTx) Commit() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit")
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockTxMockRecorder) Commit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockTx)(nil).Commit))
}

// InsertPayment mocks base method.
func (m *MockTx) InsertPayment(ctx context.Context, p NewPayment) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertPayment", ctx, p)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertPayment indicates an expected call of InsertPayment.
func (mr *MockTxMockRecorder) InsertPayment(ctx, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertPayment", reflect.TypeOf((*MockTx)(nil).InsertPayment), ctx, p)
}

// LockLoan mocks base method.
func (m *MockTx) LockLoan(ctx context.Context, loanID int64) (LoanRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockLoan", ctx, loanID)
	ret0, _ := ret[0].(LoanRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LockLoan indicates an expected call of LockLoan.
func (mr *MockTxMockRecorder) LockLoan(ctx, loanID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockLoan", reflect.TypeOf((*MockTx)(nil).LockLoan), ctx, loanID)
}

// MarkInstallmentPaid mocks base method.
func (m *MockTx) MarkInstallmentPaid(ctx context.Context, loanID int64, week int, paymentID int64, paidAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkInstallmentPaid", ctx, loanID, week, paymentID, paidAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkInstallmentPaid indicates an expected call of MarkInstallmentPaid.
func (mr *MockTxMockRecorder) MarkInstallmentPaid(ctx, loanID, week, paymentID, paidAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkInstallmentPaid", reflect.TypeOf((*MockTx)(nil).MarkInstallmentPaid), ctx, loanID, week, paymentID, paidAt)
}

// OldestPendingInstallment mocks base method.
func (m *MockTx) OldestPendingInstallment(ctx context.Context, loanID int64) (Installment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OldestPendingInstallment", ctx, loanID)
	ret0, _ := ret[0].(Installment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OldestPendingInstallment indicates an expected call of OldestPendingInstallment.
func (mr *MockTxMockRecorder) OldestPendingInstallment(ctx, loanID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OldestPendingInstallment", reflect.TypeOf((*MockTx)(nil).OldestPendingInstallment), ctx, loanID)
}

// OverdueCount mocks base method.
func (m *MockTx) OverdueCount(ctx context.Context, loanID int64, asOfDate time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OverdueCount", ctx, loanID, asOfDate)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OverdueCount indicates an expected call of OverdueCount.
func (mr *MockTxMockRecorder) OverdueCount(ctx, loanID, asOfDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OverdueCount", reflect.TypeOf((*MockTx)(nil).OverdueCount), ctx, loanID, asOfDate)
}

// PendingTotal mocks base method.
func (m *MockTx) PendingTotal(ctx context.Context, loanID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PendingTotal", ctx, loanID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PendingTotal indicates an expected call of PendingTotal.
func (mr *MockTxMockRecorder) PendingTotal(ctx, loanID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PendingTotal", reflect.TypeOf((*MockTx)(nil).PendingTotal), ctx, loanID)
}

// Rollback mocks base method.
func (m *MockTx) Rollback() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback")
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockTxMockRecorder) Rollback() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockTx)(nil).Rollback))
}

// UpdateLoanStatus mocks base method.
func (m *MockTx) UpdateLoanStatus(ctx context.Context, loanID int64, status loan.Status) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLoanStatus", ctx, loanID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLoanStatus indicates an expected call of UpdateLoanStatus.
func (mr *MockTxMockRecorder) UpdateLoanStatus(ctx, loanID, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLoanStatus", reflect.TypeOf((*MockTx)(nil).UpdateLoanStatus), ctx, loanID, status)
}
