// Code generated by MockGen. DO NOT EDIT.
// Source: ./service.go

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockDBStore is a mock of DBStore interface.
type MockDBStore struct {
	ctrl     *gomock.Controller
	recorder *MockDBStoreMockRecorder
}

// MockDBStoreMockRecorder is the mock recorder for MockDBStore.
type MockDBStoreMockRecorder struct {
	mock *MockDBStore
}

// NewMockDBStore creates a new mock instance.
func NewMockDBStore(ctrl *gomock.Controller) *MockDBStore {
	mock := &MockDBStore{ctrl: ctrl}
	mock.recorder = &MockDBStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBStore) EXPECT() *MockDBStoreMockRecorder {
	return m.recorder
}

// OverdueSnapshot mocks base method.
func (m *MockDBStore) OverdueSnapshot(ctx context.Context, loanID int64, asOfDate time.Time) (Snapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OverdueSnapshot", ctx, loanID, asOfDate)
	ret0, _ := ret[0].(Snapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OverdueSnapshot indicates an expected call of OverdueSnapshot.
func (mr *MockDBStoreMockRecorder) OverdueSnapshot(ctx, loanID, asOfDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OverdueSnapshot", reflect.TypeOf((*MockDBStore)(nil).OverdueSnapshot), ctx, loanID, asOfDate)
}
